name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - docs/**
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install --pure-lock
      
      - name: Build plugin
        run: yarn build

