name: Release

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install --pure-lock
      
      - name: Build plugin
        run: yarn build

      - name: Sign Plugin
        run: npx @grafana/toolkit plugin:sign --rootUrls {{ secrets.DASHBOARD_URL }}
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}

      - name: ZIP Plugin
        run: zip plugin.zip dist -r

      - uses: PssbleTrngle/VersionManagment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: version

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.next }}
          release_name: ${{ steps.version.outputs.next }}
          body: ${{ github.event.pull_request.body }}
          prerelease: ${{ steps.version.outputs.type == 'alpha' }}

      - name: Upload Mod Jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: plugin.zip
          asset_name: day-chart-${{ steps.version.outputs.next }}.zip
          asset_content_type: application/zip