name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - docs/**
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2